version: '2'

services:
    workspace:
        build:
            context: ./
            dockerfile: workspace.dockerfile
        working_dir: /var/www
        volumes:
            - ./src:/var/www
        environment:
            - "DB_PORT=3306"
            - "DB_HOST=database"
    web:
        build:
            context: ./
            dockerfile: web.dockerfile
        working_dir: /var/www
        volumes_from:
            - workspace
        ports:
            - 8080:80
    database:
        image: mysql:5.7
        volumes:
            - dbdata:/var/lib/mysql
        environment:
            - "MYSQL_DATABASE=homestead"
            - "MYSQL_USER=homestead"
            - "MYSQL_PASSWORD=thepassword"
            - "MYSQL_ROOT_PASSWORD=thepassword"
        ports:
            - "33061:3306"

volumes:
    dbdata:
